baseURL = ""
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Example"
theme = "mytheme"
buildDrafts = true
enableRobotsTXT = true
rssLimit = 100

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML"]
# taxonomyTerm = ["HTML"]
# taxonomy = ["HTML"]

[outputFormats]
[outputFormats.RSS]
# change name of rss feed
baseName = "feed"
